#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true

users:
  - default
  - name: yc-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChD/wPRvwW1GuuEDOD6SquDKQH5eWX8hs8RR8sq9shWGH/vlX/hTuIvDm6h5RhsWGonCusdzu2L79n7yllwI+BDTfsXyIpwTieh+oOBsRVkDA49nP+mXImXGCOPpy2PBgEpkgNfALUKzWcBuIP0RhSrwWRzUiJyDQDEF70ONA2N9GmcxSAEvenWg1SRNqGyQx3tVGzcvus3rqOG8l81a7mm/ppEw2ixuUJdfH8r1mPNlEJ2yFs6/NC/IwCy/hCKpEqP7ZKCwNqYeSn9nP2FuElbUYm7I2rPcTd0oU2AjUL/bApAJKkObwfOkZWtlRxpOduLk3yIzALU4Rs9DscQv+7x3ifrMkB4XIX239L80C9f3rHE/mpA6CI19z8M0SAGfYX4ZmCLd8HfxbgN/ngzzNWUTFrtqwcvXev54QpBt7c8a7IJj3x8lnil8WZead/HTBH+TyARzZp4b0gtQzHQzuyEQuq92cDW3vGPutV7Tccc4vDn74C+DqmcH4BUCdqExc= appuser"

runcmd:
  - sudo apt update
  - sudo apt install -y ruby-full ruby-bundler build-essential
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - sudo apt-get update
  - apt-get install -y apt-transport-https ca-certificates
  - sudo apt-get install -y mongodb-org
  - sudo systemctl start mongod
  - sudo systemctl enable mongod
  - sudo apt-get install -y git
  - cd
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit
  - bundle install
  - puma -d
